### ISSUE TITLE
Feature request: ability to use priority 2

### ISSUE THREAD

**Issue by WilliamDEdwards** [nixwiz/sensu-go-pushover-handler#15]
I would like to use Pushover's priority 2 (emergency) so messages are repeated until acknowledged. Currently, it is only possible to use priority 0 and 1, as the Pushover API requires the `expire` and `retry` parameters to be set when POSTing priority 2 messages. Having `sensu-go-pushover-handler` support sending these required parameters would allow users to send messages with priority 2.

**Comment by nixwiz** [comment]
Thanks for the request.  It should be in the 0.7.0 release now.
