### ISSUE TITLE
Release SHA doesn't match with bosai SHA.

### ISSUE THREAD

**Issue by jBRNDnl** [nixwiz/sensu-go-pushover-handler#5]
Hi,
Sorry for bothering. But the SHA512 in de release file doesn't match the SHA512 file bonsai has for the 0.4.1 release.

Release txt:
`018fa168f45e79b9bd9a55b77355b61192f2f5362735322374df12638b18d4872eed561b6676b1865604b0f145752ab964f371cc2442040a3340fd567c96783a  sensu-go-pushover-handler_0.4.1_linux_amd64.tar.gz 
`
Bonsai site:
`8f11a4ecbe1e3fcf4c56d5fd42b4af88a9399cecb8035e12af29c8740b3d2e6228cb1259805f5f967e63ac6c8cb9d5f505433246c0b7e5415f01f0327ebfd6d3 linux amd64`

Could you perhaps rebuild the package via travis or via the bonsai site so the update gets detected.

**Comment by nixwiz** [comment]
The release text has the correct SHA512 checksum.  We are investigating why it is reporting the incorrect sum on the bonsai site.

**Comment by nixwiz** [comment]
The issue with the incorrect SHA has been fixed on the bonsai site.
